/* 
Given an array arr[] of N positive elements. 
The task is to find the Maximum AND Value generated by any pair(arri, arrj) from the array such that i != j.
Note: AND is bitwise '&' operator.
Input: 
N = 4
arr[] = {4, 8, 12, 16}
Output: 8
Explanation:
Pair (8,12) has the Maximum AND Value 8.
*/
import java.util.Scanner;

class MaxAndValue{
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter the number of elements in the array:");
        int n = scanner.nextInt();
        if (n < 2) {
            System.out.println("Array must contain at least two elements.");
            return;
        }
        System.out.println("Enter the elements of the array:");
        int[] arr = new int[n];
        for (int i = 0; i < n; i++) {
            arr[i] = scanner.nextInt();
        }
        scanner.close();
        System.out.println("Maximum AND value: " + maxAND(arr, n));
    }
    public static int maxAND (int arr[], int N) {
        
        // Your code here
        // You can add extra function (if required)
        int res=0,count,newNum;
        for(int bitPos=16;bitPos>=0;bitPos--){
            newNum=(1<<bitPos);// 2^16 means 10000000000
            count=getMatchCount(res|newNum,arr);
            if(count>=2)
                res = (res | newNum);
        }
        return res;
    }
    
    private static int getMatchCount(int pattern, int arr[]){
        int count=0;
        for(int i=0;i<arr.length;i++){
            if((pattern & arr[i])==pattern)
                count++;
        }
        return count;
    }
}